# Generated by Django 5.2.6 on 2026-02-26 18:38

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gate_id", models.CharField(max_length=10, unique=True)),
                ("terminal", models.CharField(max_length=10)),
                ("capacity", models.CharField(default="narrow-body", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "AVAILABLE"),
                            ("occupied", "OCCUPIED"),
                            ("maintenance", "MAINTENANCE"),
                            ("closed", "CLOSED"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["gate_id"],
            },
        ),
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("config", models.JSONField(default=dict)),
                (
                    "current_time",
                    models.DateTimeField(default=datetime.datetime(2026, 1, 1, 0, 0)),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=10, unique=True)),
                ("origin", models.CharField(max_length=3)),
                ("destination", models.CharField(max_length=3)),
                ("scheduled_departure", models.DateTimeField()),
                ("actual_departure", models.DateTimeField(blank=True, null=True)),
                ("scheduled_arrival", models.DateTimeField()),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "SCHEDULED"),
                            ("boarding", "BOARDING"),
                            ("departed", "DEPARTED"),
                            ("arrived", "ARRIVED"),
                            ("delayed", "DELAYED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("delay_minutes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flights",
                        to="core.gate",
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="core.simulationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_departure"],
            },
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("passport_number", models.CharField(max_length=20, unique=True)),
                ("seat_number", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("checked_in", "CHECKED_IN"),
                            ("boarded", "BOARDED"),
                            ("arrived", "ARRIVED"),
                            ("no_show", "NO_SHOW"),
                        ],
                        default="checked_in",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="core.flight",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("timestamp", models.DateTimeField()),
                ("event_type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "INFO"),
                            ("warning", "WARNING"),
                            ("error", "ERROR"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_logs",
                        to="core.flight",
                    ),
                ),
                (
                    "simulation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="core.simulationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp", "event_type"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("employee_number", models.CharField(max_length=20, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("pilot", "PILOT"),
                            ("co_pilot", "CO_PILOT"),
                            ("cabin_crew", "CABIN_CREW"),
                            ("ground_crew", "GROUND_CREW"),
                            ("security", "SECURITY"),
                            ("cleaning", "CLEANING"),
                            ("maintenance", "MAINTENANCE"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "certification",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "simulation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="core.simulationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
