# Generated by Django 5.2.6 on 2026-02-28 05:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="eventlog",
            name="simulation_run",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="simulation_run",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="simulation_run",
        ),
        migrations.AlterModelOptions(
            name="eventlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="flight",
            name="aircraft_type",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="flight",
            name="airline",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="passenger",
            name="checked_bags",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="passenger",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="passenger",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="staff",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="staff",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="flight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="core.flight",
            ),
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="timestamp",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name="SimulationRun",
        ),
    ]
