# Generated by Django 5.2.6 on 2026-02-28 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_airport_remove_eventlog_simulation_run_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "MONTHLY"),
                            ("quarterly", "QUARTERLY"),
                            ("annual", "ANNUAL"),
                            ("custom", "CUSTOM"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "DRAFT"),
                            ("in_progress", "IN_PROGRESS"),
                            ("completed", "COMPLETED"),
                            ("approved", "APPROVED"),
                            ("rejected", "REJECTED"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("passenger_count", models.IntegerField(default=0)),
                ("flight_count", models.IntegerField(default=0)),
                (
                    "fuel_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "parking_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "retail_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "landing_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cargo_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "other_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "security_costs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "maintenance_costs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "operational_costs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "staff_costs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "utility_costs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "other_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("assessment_notes", models.TextField(blank=True, default="")),
                (
                    "assessed_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_assessments",
                        to="core.airport",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {
                    ("airport", "period_type", "start_date", "end_date")
                },
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("fiscal_summary", "FISCAL_SUMMARY"),
                            ("operational", "OPERATIONAL"),
                            ("passenger", "PASSENGER"),
                            ("financial", "FINANCIAL"),
                            ("performance", "PERFORMANCE"),
                            ("compliance", "COMPLIANCE"),
                        ],
                        default="fiscal_summary",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        default="html",
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=500)),
                ("content", models.JSONField(blank=True, default=dict)),
                (
                    "generated_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_generated", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.airport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "INVOICE"),
                            ("receipt", "RECEIPT"),
                            ("certificate", "CERTIFICATE"),
                            ("permit", "PERMIT"),
                            ("report", "REPORT"),
                            ("agreement", "AGREEMENT"),
                            ("memo", "MEMO"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=500)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("is_template", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.airport",
                    ),
                ),
                (
                    "fiscal_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.fiscalassessment",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.report",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
