# Generated by Django 5.2.6 on 2026-02-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_fiscalassessment_report_document"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["document_type"], name="doc_type_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["airport", "-created_at"], name="doc_airport_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["is_template"], name="doc_template_idx"),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(fields=["-timestamp"], name="event_timestamp_idx"),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(fields=["event_type"], name="event_type_idx"),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(fields=["severity"], name="event_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["flight", "-timestamp"], name="event_flight_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["event_type", "-timestamp"], name="event_type_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalassessment",
            index=models.Index(
                fields=["airport", "-start_date"], name="fiscal_airport_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalassessment",
            index=models.Index(fields=["status"], name="fiscal_status_idx"),
        ),
        migrations.AddIndex(
            model_name="fiscalassessment",
            index=models.Index(fields=["period_type"], name="fiscal_period_idx"),
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(
                fields=["scheduled_departure"], name="flight_depart_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(fields=["status"], name="flight_status_idx"),
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(
                fields=["gate", "status", "scheduled_departure"],
                name="flight_gate_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(
                fields=["origin", "destination"], name="flight_route_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(fields=["airline"], name="flight_airline_idx"),
        ),
        migrations.AddIndex(
            model_name="gate",
            index=models.Index(fields=["status"], name="gate_status_idx"),
        ),
        migrations.AddIndex(
            model_name="gate",
            index=models.Index(fields=["terminal"], name="gate_terminal_idx"),
        ),
        migrations.AddIndex(
            model_name="gate",
            index=models.Index(
                fields=["terminal", "status"], name="gate_term_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passenger",
            index=models.Index(
                fields=["flight", "status"], name="pass_flight_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passenger",
            index=models.Index(fields=["passport_number"], name="pass_passport_idx"),
        ),
        migrations.AddIndex(
            model_name="passenger",
            index=models.Index(fields=["status"], name="pass_status_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["airport", "-created_at"], name="report_airport_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["report_type"], name="report_type_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["period_start", "period_end"], name="report_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["is_generated"], name="report_generated_idx"),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(fields=["role"], name="staff_role_idx"),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["is_available", "role"], name="staff_avail_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(fields=["employee_number"], name="staff_emp_idx"),
        ),
    ]
