# Generated by Django 5.2.6 on 2026-02-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("pilot", "PILOT"),
                            ("co_pilot", "CO_PILOT"),
                            ("cabin_crew", "CABIN_CREW"),
                            ("ground_crew", "GROUND_CREW"),
                            ("security", "SECURITY"),
                            ("cleaning", "CLEANING"),
                            ("maintenance", "MAINTENANCE"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="core.flight",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.staff",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["staff", "flight"], name="staff_flight_idx"),
                    models.Index(fields=["flight"], name="assignment_flight_idx"),
                    models.Index(
                        fields=["staff", "assigned_at"], name="staff_assign_idx"
                    ),
                ],
                "unique_together": {("staff", "flight", "assignment_type")},
            },
        ),
    ]
