# Generated by Django 5.2.6 on 2026-03-01 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_staff_assignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tail_number", models.CharField(max_length=20, unique=True)),
                (
                    "aircraft_type",
                    models.CharField(
                        choices=[
                            ("narrow_body", "NARROW_BODY"),
                            ("wide_body", "WIDE_BODY"),
                            ("regional", "REGIONAL"),
                            ("cargo", "CARGO"),
                        ],
                        default="narrow_body",
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("manufacturer", models.CharField(max_length=50)),
                ("capacity_passengers", models.IntegerField(default=0)),
                (
                    "capacity_cargo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "ACTIVE"),
                            ("maintenance", "MAINTENANCE"),
                            ("retired", "RETIRED"),
                            ("stored", "STORED"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "registration_country",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("year_manufactured", models.IntegerField(blank=True, null=True)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_due", models.DateField(blank=True, null=True)),
                (
                    "total_flight_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tail_number"],
                "indexes": [
                    models.Index(fields=["status"], name="aircraft_status_idx"),
                    models.Index(fields=["aircraft_type"], name="aircraft_type_idx"),
                    models.Index(fields=["tail_number"], name="aircraft_tail_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CrewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "crew_type",
                    models.CharField(
                        choices=[
                            ("pilot", "PILOT"),
                            ("first_officer", "FIRST_OFFICER"),
                            ("flight_attendant", "FLIGHT_ATTENDANT"),
                            ("lead_flight_attendant", "LEAD_FATTENDANT"),
                            ("flight_engineer", "FLIGHT_ENGINEER"),
                        ],
                        default="flight_attendant",
                        max_length=25,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("license_expiry", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "AVAILABLE"),
                            ("assigned", "ASSIGNED"),
                            ("on_leave", "ON_LEAVE"),
                            ("unavailable", "UNAVAILABLE"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "total_flight_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("rank", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_airport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crew_base",
                        to="core.airport",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["status"], name="crew_status_idx"),
                    models.Index(fields=["crew_type"], name="crew_type_idx"),
                    models.Index(fields=["employee_id"], name="crew_emp_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("safety", "SAFETY"),
                            ("security", "SECURITY"),
                            ("operational", "OPERATIONAL"),
                            ("environmental", "ENVIRONMENTAL"),
                            ("equipment", "EQUIPMENT"),
                            ("other", "OTHER"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "LOW"),
                            ("medium", "MEDIUM"),
                            ("high", "HIGH"),
                            ("critical", "CRITICAL"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "REPORTED"),
                            ("investigating", "INVESTIGATING"),
                            ("resolved", "RESOLVED"),
                            ("closed", "CLOSED"),
                        ],
                        default="reported",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                ("date_occurred", models.DateTimeField()),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
                ("date_resolved", models.DateTimeField(blank=True, null=True)),
                ("root_cause", models.TextField(blank=True, default="")),
                ("corrective_action", models.TextField(blank=True, default="")),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents",
                        to="core.staff",
                    ),
                ),
                (
                    "related_flight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="core.flight",
                    ),
                ),
                (
                    "related_gate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="core.gate",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to="core.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_occurred"],
                "indexes": [
                    models.Index(fields=["incident_type"], name="inc_type_idx"),
                    models.Index(fields=["severity"], name="inc_severity_idx"),
                    models.Index(fields=["status"], name="inc_status_idx"),
                    models.Index(fields=["date_occurred"], name="inc_date_idx"),
                    models.Index(fields=["date_reported"], name="inc_reported_idx"),
                    models.Index(fields=["related_flight"], name="inc_flight_idx"),
                    models.Index(fields=["related_gate"], name="inc_gate_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("gate", "GATE"),
                            ("ground_equipment", "GROUND_EQUIPMENT"),
                            ("baggage_system", "BAGGAGE_SYSTEM"),
                            ("security_equipment", "SECURITY_EQUIPMENT"),
                            ("hvac", "HVAC"),
                            ("lighting", "LIGHTING"),
                            ("other", "OTHER"),
                        ],
                        max_length=30,
                    ),
                ),
                ("equipment_id", models.CharField(max_length=50)),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("routine", "ROUTINE"),
                            ("scheduled", "SCHEDULED"),
                            ("unscheduled", "UNSCHEDULED"),
                            ("inspection", "INSPECTION"),
                            ("repair", "REPAIR"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("in_progress", "IN_PROGRESS"),
                            ("completed", "COMPLETED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("parts_replaced", models.JSONField(blank=True, default=list)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_logs",
                        to="core.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["equipment_type", "equipment_id"],
                        name="maint_equip_idx",
                    ),
                    models.Index(fields=["status"], name="maint_status_idx"),
                    models.Index(fields=["maintenance_type"], name="maint_type_idx"),
                    models.Index(fields=["started_at"], name="maint_started_idx"),
                ],
            },
        ),
    ]
