# Generated by Django 5.2.6 on 2026-03-04 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_api_and_websocket_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("view", "View"),
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("export", "Export"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventlog",
            name="ip_address",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
        migrations.AddField(
            model_name="eventlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="event_user_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(fields=["action"], name="event_action_idx"),
        ),
    ]
