# Generated by Django 5.2.6 on 2026-03-14 13:02

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_user_action_fields_to_eventlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("fiscal_summary", "FISCAL_SUMMARY"),
                            ("operational", "OPERATIONAL"),
                            ("passenger", "PASSENGER"),
                            ("financial", "FINANCIAL"),
                            ("performance", "PERFORMANCE"),
                            ("compliance", "COMPLIANCE"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="0=Monday, 6=Sunday (for weekly frequency)",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True, help_text="1-31 (for monthly frequency)", null=True
                    ),
                ),
                (
                    "hour",
                    models.IntegerField(
                        default=6, help_text="Hour of day (0-23) to generate report"
                    ),
                ),
                (
                    "recipients",
                    models.TextField(help_text="Comma-separated email addresses"),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        default=core.models.ReportFormat["PDF"],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to="core.airport",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["is_active"], name="schedule_active_idx"),
                    models.Index(fields=["frequency"], name="schedule_freq_idx"),
                    models.Index(fields=["next_run"], name="schedule_next_idx"),
                ],
            },
        ),
    ]
