# Generated by Django 5.2.6 on 2026-03-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_report_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("min_staff", models.PositiveIntegerField(default=1)),
                ("max_staff", models.PositiveIntegerField(default=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(fields=["is_active"], name="shift_active_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Baggage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_number", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("checked_in", "Checked In"),
                            ("screened", "Screened"),
                            ("sorted", "Sorted"),
                            ("loaded", "Loaded"),
                            ("in_transit", "In Transit"),
                            ("unloaded", "Unloaded"),
                            ("at_belt", "At Claim Belt"),
                            ("claimed", "Claimed"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                        ],
                        default="checked_in",
                        max_length=20,
                    ),
                ),
                ("origin", models.CharField(max_length=3)),
                ("destination", models.CharField(max_length=3)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in kg", max_digits=5
                    ),
                ),
                ("pieces", models.PositiveIntegerField(default=1)),
                (
                    "special_handling",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("checked_in_at", models.DateTimeField(auto_now_add=True)),
                ("screened_at", models.DateTimeField(blank=True, null=True)),
                ("loaded_at", models.DateTimeField(blank=True, null=True)),
                ("unloaded_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baggage",
                        to="core.flight",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baggage",
                        to="core.passenger",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_in_at"],
                "indexes": [
                    models.Index(fields=["status"], name="baggage_status_idx"),
                    models.Index(fields=["flight"], name="baggage_flight_idx"),
                    models.Index(fields=["passenger"], name="baggage_passenger_idx"),
                    models.Index(fields=["tag_number"], name="baggage_tag_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.shift",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to="core.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "shift__start_time"],
                "indexes": [
                    models.Index(fields=["date"], name="shift_assign_date_idx"),
                    models.Index(fields=["status"], name="shift_assign_status_idx"),
                    models.Index(
                        fields=["staff", "date"], name="shift_assign_staff_date_idx"
                    ),
                ],
                "unique_together": {("staff", "date", "shift")},
            },
        ),
    ]
