# Generated by Django 5.2.6 on 2026-03-14 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_shift_baggage_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("jet_a", "Jet A"),
                            ("jet_a1", "Jet A-1"),
                            ("avgas", "Avgas 100LL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("storage_tank", models.CharField(max_length=50)),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=2, help_text="Liters", max_digits=10
                    ),
                ),
                (
                    "current_level",
                    models.DecimalField(
                        decimal_places=2, help_text="Liters", max_digits=10
                    ),
                ),
                (
                    "min_level",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Liters", max_digits=10
                    ),
                ),
                ("last_delivery", models.DateTimeField(blank=True, null=True)),
                (
                    "last_delivery_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_inventories",
                        to="core.airport",
                    ),
                ),
            ],
            options={
                "ordering": ["airport", "fuel_type"],
            },
        ),
        migrations.CreateModel(
            name="FuelDispensing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Liters", max_digits=8
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("truck_id", models.CharField(blank=True, default="", max_length=20)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_dispensing",
                        to="core.flight",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_dispensing_records",
                        to="core.staff",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensing_records",
                        to="core.fuelinventory",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("gate", "Gate"),
                            ("vehicle", "Vehicle"),
                            ("facility", "Facility"),
                            ("equipment", "Equipment"),
                            ("hvac", "HVAC System"),
                            ("electrical", "Electrical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipment_id",
                    models.CharField(help_text="Equipment identifier", max_length=50),
                ),
                ("maintenance_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_performed", models.DateTimeField(blank=True, null=True)),
                ("next_due", models.DateTimeField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_schedules",
                        to="core.airport",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_maintenance",
                        to="core.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["next_due", "priority"],
            },
        ),
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("thunderstorm", "Thunderstorm"),
                            ("tornado", "Tornado"),
                            ("hurricane", "Hurricane"),
                            ("heavy_rain", "Heavy Rain"),
                            ("heavy_snow", "Heavy Snow"),
                            ("fog", "Fog"),
                            ("ice", "Ice"),
                            ("high_wind", "High Wind"),
                            ("heat_wave", "Heat Wave"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("severe", "Severe"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_weather_alerts",
                        to="core.staff",
                    ),
                ),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_alerts",
                        to="core.airport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "feels_like",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("humidity", models.PositiveIntegerField(blank=True, null=True)),
                ("pressure", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "wind_speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "wind_direction",
                    models.PositiveIntegerField(
                        blank=True, help_text="Degrees 0-360", null=True
                    ),
                ),
                (
                    "wind_gust",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "visibility",
                    models.PositiveIntegerField(
                        blank=True, help_text="Meters", null=True
                    ),
                ),
                ("cloud_cover", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "precipitation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weather_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "weather_description",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("severe", "Severe"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "delay_impact",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated delay in minutes"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_conditions",
                        to="core.airport",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="fuelinventory",
            index=models.Index(
                fields=["airport", "fuel_type"], name="fuel_airport_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fuelinventory",
            index=models.Index(fields=["fuel_type"], name="fuel_type_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="fuelinventory",
            unique_together={("airport", "fuel_type", "storage_tank")},
        ),
        migrations.AddIndex(
            model_name="fueldispensing",
            index=models.Index(fields=["flight"], name="fuel_disp_flight_idx"),
        ),
        migrations.AddIndex(
            model_name="fueldispensing",
            index=models.Index(fields=["inventory"], name="fuel_disp_inv_idx"),
        ),
        migrations.AddIndex(
            model_name="fueldispensing",
            index=models.Index(fields=["start_time"], name="fuel_disp_time_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenanceschedule",
            index=models.Index(fields=["status"], name="maint_sched_status_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenanceschedule",
            index=models.Index(fields=["next_due"], name="maint_sched_due_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenanceschedule",
            index=models.Index(
                fields=["equipment_type", "equipment_id"], name="maint_sched_equip_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceschedule",
            index=models.Index(
                fields=["airport", "status"], name="maint_sched_airport_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weatheralert",
            index=models.Index(
                fields=["airport", "is_active"], name="alert_airport_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weatheralert",
            index=models.Index(fields=["is_active"], name="alert_active_idx"),
        ),
        migrations.AddIndex(
            model_name="weatheralert",
            index=models.Index(fields=["alert_type"], name="alert_type_idx"),
        ),
        migrations.AddIndex(
            model_name="weathercondition",
            index=models.Index(
                fields=["airport", "-timestamp"], name="weather_airport_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weathercondition",
            index=models.Index(fields=["severity"], name="weather_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="weathercondition",
            index=models.Index(fields=["timestamp"], name="weather_time_idx"),
        ),
    ]
