# Generated by Django 5.2.6 on 2026-03-14 14:01

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_weather_fuel_maintenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=50)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Yes/No"),
                            ("choice", "Dropdown"),
                            ("email", "Email"),
                            ("url", "URL"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("choices", models.JSONField(blank=True, default=list)),
                (
                    "default_value",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("help_text", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["model_name", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("model_name", models.CharField(max_length=50)),
                ("value", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="flight",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["flight_number", "airline", "origin", "destination"],
                name="flight_search_gin_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customfield",
            unique_together={("model_name", "name")},
        ),
        migrations.AddField(
            model_name="customfieldvalue",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="core.customfield",
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="core_custom_model_n_9d6fda_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customfieldvalue",
            unique_together={("field", "object_id", "model_name")},
        ),
    ]
