# Generated by Django 5.2.6 on 2026-03-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Airport latitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Airport longitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
    ]
