"""
Django settings for airport_sim project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if SECRET_KEY is None:
    # Fail fast if SECRET_KEY is not set - do not use insecure fallbacks
    raise ValueError("SECRET_KEY environment variable is not set. This is required for security.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',  # Token authentication
    'corsheaders',
    'channels',  # WebSocket support
    'django_q',  # Background tasks
    # Local apps
    'core',
]

# Django-Q Configuration
Q_CLUSTER = {
    'name': 'BlueFalcon_Q',
    'workers': 4,
    'recycle': 500,
    'timeout': 60,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default', # Using ORM for simplicity in this dev environment
}

MIDDLEWARE = [
    # Security middleware - must be at top
    'django.middleware.security.SecurityMiddleware',
    
    # WhiteNoise for static files (must be after SecurityMiddleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    # CORS support (for API versioning)
    'corsheaders.middleware.CorsMiddleware',
    
    # Common middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    
    # CSRF protection
    'django.middleware.csrf.CsrfViewMiddleware',
    
    # Authentication
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # Messages
    'django.contrib.messages.middleware.MessageMiddleware',
    
    # Clickjacking protection
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Custom middleware for request tracking in signals
    'core.middleware.RequestMiddleware',
    
    # Honeypot protection middleware
    'core.middleware.HoneypotMiddleware',
    'core.middleware.HoneypotTokenMiddleware',
]

ROOT_URLCONF = 'airport_sim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'airport_sim.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# PostgreSQL configuration with environment variable support

db_engine = os.environ.get('DATABASE_ENGINE', 'django.db.backends.postgresql')

if db_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.environ.get('DATABASE_NAME', 'db.sqlite3'),
            'OPTIONS': {
                'timeout': 30,
            },
            'CONN_MAX_AGE': 600,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': db_engine,
            'NAME': os.environ.get('DATABASE_NAME', 'airport_db'),
            'USER': os.environ.get('DATABASE_USER', 'postgres'),
            'PASSWORD': os.environ.get('DATABASE_PASSWORD', ''),
            'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
            'PORT': os.environ.get('DATABASE_PORT', '5432'),
            'OPTIONS': {
                'sslmode': os.environ.get('DATABASE_SSL_MODE', 'prefer'),
                'connect_timeout': 10,
            },
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# WhiteNoise for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Additional static files locations
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Media files (user uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Caching configuration for scalability
# https://docs.djangoproject.com/en/5.1/topics/cache/
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
        },
        'TIMEOUT': 300,  # 5 minutes default
    }
}

# For production with Redis:
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django.core.cache.backends.redis.RedisClient',
#         },
#         'TIMEOUT': 300,
#     }
# }

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF configuration
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Security settings for production
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() in ('true', '1', 'yes')
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Content Security Policy - Whitelist approach
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

# Referrer Policy - Whitelist
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Django Admin - Require superuser for admin access (defense in depth)
# This setting requires Django 4.2+
# Even though we use RestrictedAdminSite in urls.py, this provides additional protection
ADMIN_REQUIRE_SUPERUSER = True

# Whitelist-based ALLOWED_HOSTS validation
# Split by comma and strip whitespace
_raw_hosts = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = [host.strip() for host in _raw_hosts if host.strip()]

# Validate ALLOWED_HOSTS - only allow valid hostnames or IP addresses
import re
_allowed_pattern = re.compile(r'^([a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$|^localhost$|^127\.0\.0\.1$|^::1$')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'honeypot.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Custom logger for fiscal assessment audit trail
        'fiscal_assessment_audit': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Custom logger for CSV import operations
        'csv_import': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Honeypot logger - captures all honeypot detection events
        'honeypot': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',  # Log warnings and above for honeypot events
            'propagate': False,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

for host in ALLOWED_HOSTS:
    if not _allowed_pattern.match(host):
        raise ValueError(f"Invalid ALLOWED_HOSTS entry: {host}")
# File upload whitelist - Only allow safe file extensions
ALLOWED_FILE_EXTENSIONS = ['.csv', '.txt', '.pdf', '.png', '.jpg', '.jpeg', '.gif', '.doc', '.docx', '.xls', '.xlsx']
MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB max

# File upload settings with enhanced security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB - files larger will be streamed to disk

# Allowed MIME types (beyond just extensions)
ALLOWED_MIME_TYPES = [
    'text/csv',
    'text/plain',
    'application/pdf',
    'image/png',
    'image/jpeg',
    'image/gif',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/json',
    'application/zip',
]

# Chunked upload settings
CHUNKED_UPLOAD_ENABLED = True
CHUNKED_UPLOAD_CHUNK_SIZE = 1024 * 1024  # 1MB chunks
CHUNKED_UPLOAD_MAX_CHUNKS = 100  # Maximum 100 chunks (100MB max)

# File validation settings
FILE_VALIDATION_STRICT = True  # Validate MIME types, not just extensions
FILE_SCAN_ON_UPLOAD = False  # Enable virus scanning (requires ClamAV or similar)

# Enable honeypot protection
HONEYPOT_ENABLED = True

# Honeypot endpoint paths that trigger alerts when accessed
HONEYPOT_PATHS = [
    '/admin/secret-panel/',
    '/api/internal/debug/',
    '/api/backup/',
    '/api/v1/admin/',
    '/wp-admin/',
    '/phpmyadmin/',
    '/server-status/',
    '/.git/config',
    '/.env',
    '/api/debug/',
    '/internal/api/',
]

# Rate limiting for honeypot triggers
HONEYPOT_RATE_LIMIT_WINDOW = 60  # seconds
HONEYPOT_RATE_LIMIT_MAX = 3  # max triggers per IP in window

# Enable honeypot token generation for forms
HONEYPOT_TOKEN_ENABLED = True

# Time delay for repeated honeypot triggers (seconds)
HONEYPOT_DELAY_ON_TRIGGER = 2

# Block IPs that trigger honeypots multiple times
HONEYPOT_AUTO_BLOCK = True
HONEYPOT_BLOCK_THRESHOLD = 5
HONEYPOT_BLOCK_DURATION = 3600  # seconds (1 hour)

# File storage settings
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
MEDIAFILES_LOCATION = 'uploads'

# CORS whitelist - Explicitly allow specific origins
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if os.environ.get('CORS_ALLOWED_ORIGINS') else []

# Enforce the whitelist - must be explicitly set to False to prevent accidental exposure
CORS_ALLOW_ALL_ORIGINS = False

# Additional CORS security settings
CORS_EXPOSE_HEADERS = ['Content-Type', 'Authorization']
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']

# Require CORS for credentials
CORS_ALLOW_CREDENTIALS = True

# Whitelist for content types - Only allow safe content types
DEFAULT_CONTENT_TYPE_OPTIONS = {'X-Content-Type-Options': 'nosniff'}

# Authentication backends - Explicit whitelist
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Password hashers
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# DJANGO REST FRAMEWORK CONFIGURATION (API Versioning)
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_FILTER_BACKEND': 'django_filters.rest_framework.DjangoFilterBackend',
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Stateless token auth - CSRF exempt
        'rest_framework.authentication.SessionAuthentication',  # Requires CSRF - for browser clients
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/day',
        'user': '10000/day',
    },
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# DJANGO CHANNELS CONFIGURATION (WebSocket Support)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
        # For production with Redis:
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     'hosts': [os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')],
        # },
    }
}

# ASGI application for WebSocket routing
ASGI_APPLICATION = 'airport_sim.asgi.application'

# Logins
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
